package org.limir.models.enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    ADD_CAR,
    DELETE_CAR,
    UPDATE_CAR,
    READ_CARS,
    READ_CAR_BY_MODEL,
    ADD_COMPANY,
    READ_COMPANY,
    READ_COMPANIES,
    PURCHASE_ORDER,
    READ_USER_ORDERS,
    READ_ORDERS,
    FIND_COMPANY_BY_NAME,
    FIND_PERSON_BY_SURNAME,
    ADD_EMPLOYEE,
    READ_EMPLOYEES,
    DELETE_COMPANY_BY_NAME,
    DELETE_EMPLOYEE,
    READ_USERS
}
